In [101]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [63]:
import requests #импортируем модуль
f=open(r'D:\file_bdseo.xml',"wb") #открываем файл для записи, в режиме wb
ufr = requests.get("http://www.casos.cs.cmu.edu/computational_tools/datasets/external/padgett/padgett.xml") #делаем запрос
f.write(ufr.content) #записываем содержимое в файл; как видите - content запроса
f.close()

In [64]:
#from lxml import objectify
#xml_data = objectify.parse('D:\file_bdseo.xml')
with open(r"D:\file_bdseo.xml") as f:
    xml_data = f.read()

In [65]:
xml_data

'<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><DynamicNetwork>    <MetaNetwork>        <nodes>            <nodeclass type="agent" id="agent">                <node id="ACCIAIUOL" />                <node id="ALBIZZI" />                <node id="BARBADORI" />                <node id="BISCHERI" />                <node id="CASTELLAN" />                <node id="GINORI" />                <node id="GUADAGNI" />                <node id="LAMBERTES" />                <node id="MEDICI" />                <node id="PAZZI" />                <node id="PERUZZI" />                <node id="PUCCI" />                <node id="RIDOLFI" />                <node id="SALVIATI" />                <node id="STROZZI" />                <node id="TORNABUON" />            </nodeclass>        </nodes>        <networks>            <network sourceType="agent" targetType="agent" id="PADGM">                <link source="ACCIAIUOL" target="ACCIAIUOL" type="double" value="0.0000" />                <link source="

In [82]:
import xml.etree.ElementTree as ET

class XML2DataFrame:

    def __init__(self, xml_data):
        self.root = ET.XML(xml_data)
        self.root=self.root[0][1][0]
        print(self.root.getchildren())
        #self.root=self.root.MetaNetwork.networks

    def parse_root(self, root):
        return [self.parse_element(child) for child in iter(root)]

    def parse_element(self, element, parsed=None):
        if parsed is None:
            parsed = dict()
        for key in element.keys():
            parsed[key] = element.attrib.get(key)
        if element.text:
            parsed[element.tag] = element.text
        for child in list(element):
            self.parse_element(child, parsed)
        return parsed

    def process_data(self):
        structure_data = self.parse_root(self.root)
        return pd.DataFrame(structure_data)

xml2df = XML2DataFrame(xml_data)
df = xml2df.process_data()

[<Element 'link' at 0x7f8814ed0360>, <Element 'link' at 0x7f8814ed0630>, <Element 'link' at 0x7f884b7379a0>, <Element 'link' at 0x7f8814e80810>, <Element 'link' at 0x7f8814e807c0>, <Element 'link' at 0x7f8814e80cc0>, <Element 'link' at 0x7f8814e80130>, <Element 'link' at 0x7f8814e80950>, <Element 'link' at 0x7f8814e80c20>, <Element 'link' at 0x7f8814e80db0>, <Element 'link' at 0x7f8814e80ef0>, <Element 'link' at 0x7f8814e801d0>, <Element 'link' at 0x7f8814e80bd0>, <Element 'link' at 0x7f8814e80b30>, <Element 'link' at 0x7f8814e808b0>, <Element 'link' at 0x7f8814e80180>, <Element 'link' at 0x7f8814e800e0>, <Element 'link' at 0x7f8814e80040>, <Element 'link' at 0x7f8814d478b0>, <Element 'link' at 0x7f8814d47ef0>, <Element 'link' at 0x7f8814d47ea0>, <Element 'link' at 0x7f8814d47130>, <Element 'link' at 0x7f8814d47590>, <Element 'link' at 0x7f8814d479f0>, <Element 'link' at 0x7f8814d47270>, <Element 'link' at 0x7f8814d47c20>, <Element 'link' at 0x7f8814d475e0>, <Element 'link' at 0x7f8814

<ipython-input-82-9eb3b2cc9967>:8: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  print(self.root.getchildren())


In [94]:
df[:33]

source     target    type   value
0   ACCIAIUOL  ACCIAIUOL  double  0.0000
1   ACCIAIUOL    ALBIZZI  double  0.0000
2   ACCIAIUOL  BARBADORI  double  0.0000
3   ACCIAIUOL   BISCHERI  double  0.0000
4   ACCIAIUOL  CASTELLAN  double  0.0000
5   ACCIAIUOL     GINORI  double  0.0000
6   ACCIAIUOL   GUADAGNI  double  0.0000
7   ACCIAIUOL  LAMBERTES  double  0.0000
8   ACCIAIUOL     MEDICI  double  1.0000
9   ACCIAIUOL      PAZZI  double  0.0000
10  ACCIAIUOL    PERUZZI  double  0.0000
11  ACCIAIUOL      PUCCI  double  0.0000
12  ACCIAIUOL    RIDOLFI  double  0.0000
13  ACCIAIUOL   SALVIATI  double  0.0000
14  ACCIAIUOL    STROZZI  double  0.0000
15  ACCIAIUOL  TORNABUON  double  0.0000
16    ALBIZZI  ACCIAIUOL  double  0.0000
17    ALBIZZI    ALBIZZI  double  0.0000
18    ALBIZZI  BARBADORI  double  0.0000
19    ALBIZZI   BISCHERI  double  0.0000
20    ALBIZZI  CASTELLAN  double  0.0000
21    ALBIZZI     GINORI  double  1.0000
22    ALBIZZI   GUADAGNI  double  1.0000
23    ALBIZZI  LAMBERTES  double  0.0000
24    ALBIZZI     MEDICI  double  1.0000
25    ALBIZZI      PAZZI  double  0.0000
26    ALBIZZI    PERUZZI  double  0.0000
27    ALBIZZI      PUCCI  double  0.0000
28    ALBIZZI    RIDOLFI  double  0.0000
29    ALBIZZI   SALVIATI  double  0.0000
30    ALBIZZI    STROZZI  double  0.0000
31    ALBIZZI  TORNABUON  double  0.0000
32  BARBADORI  ACCIAIUOL  double  0.0000

In [189]:
arr=df['value'].to_numpy(dtype=float)
arr=arr.reshape(16,16)
print(arr.shape)
print(arr)
arr=np.delete(arr,11,axis=0)
arr=np.delete(arr,11,axis=1)
print(arr.shape)
print(arr)

(16, 16)
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0.]]
(15, 15)
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1

In [190]:
for i in range(15):
    if arr[i].sum()!=0:
        arr[i]=arr[i]/arr[i].sum()
arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.33333333, 0.33333333, 0.        , 0.33333333, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.5       ,
        0.        , 0.        , 0.        , 0.5       , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.33333333, 0.        , 0.        , 0.        ,
        0.33333333, 0.        , 0.        , 0.33333333, 0.        ],
       [0.        , 0.        , 0.33333333, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.33333333, 0.        , 0.        , 

In [191]:
arr=arr.reshape(225)
np.putmask(arr,arr==0,1e-5)
arr=arr.reshape(15,15)

In [193]:
print(arr)

[[1.00000000e-05 1.00000000e-05 1.00000000e-05 1.00000000e-05
  1.00000000e-05 1.00000000e-05 1.00000000e-05 1.00000000e-05
  1.00000000e+00 1.00000000e-05 1.00000000e-05 1.00000000e-05
  1.00000000e-05 1.00000000e-05 1.00000000e-05]
 [1.00000000e-05 1.00000000e-05 1.00000000e-05 1.00000000e-05
  1.00000000e-05 3.33333333e-01 3.33333333e-01 1.00000000e-05
  3.33333333e-01 1.00000000e-05 1.00000000e-05 1.00000000e-05
  1.00000000e-05 1.00000000e-05 1.00000000e-05]
 [1.00000000e-05 1.00000000e-05 1.00000000e-05 1.00000000e-05
  5.00000000e-01 1.00000000e-05 1.00000000e-05 1.00000000e-05
  5.00000000e-01 1.00000000e-05 1.00000000e-05 1.00000000e-05
  1.00000000e-05 1.00000000e-05 1.00000000e-05]
 [1.00000000e-05 1.00000000e-05 1.00000000e-05 1.00000000e-05
  1.00000000e-05 1.00000000e-05 3.33333333e-01 1.00000000e-05
  1.00000000e-05 1.00000000e-05 3.33333333e-01 1.00000000e-05
  1.00000000e-05 3.33333333e-01 1.00000000e-05]
 [1.00000000e-05 1.00000000e-05 3.33333333e-01 1.00000000e-05
  

In [212]:
eps=1e-4
delta=6
pi=np.ones(15)/15
while delta>eps:
    psi=pi@arr
    delta=np.linalg.norm(pi-psi)
    pi=psi
    print(pi)
np.sum(pi)

[0.01112044 0.09445244 0.033342   0.05556356 0.07223022 0.02223156
 0.13334067 0.016676   0.200006   0.03334267 0.06111911 0.050008
 0.07778644 0.08889622 0.050008  ]
[0.03334233 0.0889075  0.05741835 0.07593943 0.05927626 0.0314932
 0.0833585  0.03334383 0.13151432 0.03890245 0.06482982 0.07223433
 0.06668467 0.07964791 0.083345  ]
[0.02192774 0.07425942 0.0416859  0.06236926 0.07023908 0.02964495
 0.11608166 0.02084879 0.17689544 0.03335167 0.06499173 0.06961975
 0.0608298  0.09076723 0.06684392]
[0.02949081 0.08815471 0.05290313 0.07338342 0.06520669 0.0247624
 0.08868076 0.02902926 0.14343327 0.03042429 0.06690236 0.07446235
 0.06284214 0.08908061 0.08171595]
[0.02391412 0.07084557 0.04564903 0.06674868 0.07103042 0.02939403
 0.11012123 0.02217931 0.16881389 0.03143045 0.06847458 0.07342121
 0.0543381  0.09332548 0.07090346]
[0.02814397 0.08506691 0.05182006 0.07369383 0.06898868 0.02362449
 0.09168624 0.02753921 0.14563771 0.02717851 0.06926543 0.07510818
 0.0595741  0.09323217 0.

1.0067865568254761

In [224]:
pi=np.insert(pi,11,0)
print(pi)
a=pd.DataFrame({'surname': df['source'].unique(), 'result': pi})
a

[0.02518117 0.07553492 0.05034473 0.07550417 0.07549544 0.02517185
 0.10065975 0.02518078 0.15099133 0.02517765 0.07549541 0.
 0.07550364 0.05037297 0.10065831 0.07551445]


surname    result
0   ACCIAIUOL  0.025181
1     ALBIZZI  0.075535
2   BARBADORI  0.050345
3    BISCHERI  0.075504
4   CASTELLAN  0.075495
5      GINORI  0.025172
6    GUADAGNI  0.100660
7   LAMBERTES  0.025181
8      MEDICI  0.150991
9       PAZZI  0.025178
10    PERUZZI  0.075495
11      PUCCI  0.000000
12    RIDOLFI  0.075504
13   SALVIATI  0.050373
14    STROZZI  0.100658
15  TORNABUON  0.075514

Таким образом, самым влиятельным мафиози является дон Medici.